deploy_webserver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: pinode01
      containers:
      - name: webserver
        image: bugbountytools/webserver
        ports:
        - containerPort: 80
        networkMode: "container:gluetun"
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 80
    nodePort: 8082
  type: NodePort
