apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobproducer
  labels:
    app: jobproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobproducer
  template:
    metadata:
      labels:
        app: jobproducer
    spec:
      containers:
      - name: jobproducer
        image: bugbountytools/jobproducer
        networkMode: "container:gluetun"
