apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: default
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      nodeSelector:
        kubernetes.io/hostname: pinode01
      initContainers:
      - name: init-iptables
        image: ubuntu:latest
        command:
        - /bin/sh
        - -c
        - |
          apt-get update && apt-get install -y iproute2 dnsutils
          GLUETUN_IP=$(dig +short gluetun.default.svc.cluster.local)
          if [ -z "$GLUETUN_IP" ]; then
            echo "Failed to resolve gluetun service IP"
            exit 1
          fi
          ip route add default via $GLUETUN_IP
        securityContext:
          privileged: true
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: default
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
