apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: default
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      nodeSelector:
        kubernetes.io/hostname: pinode01
      initContainers:
      - name: init-iptables
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          ip route add default via $(dig +short gluetun.default.svc.cluster.local)
      containers:
      - name: phpmyadmin
        image: bugbountytools/phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: UPLOAD_LIMIT
          value: "300M"
        - name: PMA_HOST
          value: "mysql.default.svc.cluster.local"
        - name: PMA_PORT
          value: "3306"
        - name: PMA_ARBITRARY
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: default
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
