apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun
        envFrom:
        - secretRef:
            name: pia-creds
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
spec:
  selector:
    app: gluetun
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
