apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: default
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "private internet access"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: PIA_USER
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: PIA_PASS
        - name: SERVER_REGIONS
          value: "Netherlands"
        ports:
        - containerPort: 8888
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: gluetun-volume
          mountPath: /gluetun
      volumes:
      - name: gluetun-volume
        emptyDir: {}
