apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: default
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      nodeSelector:
        kubernetes.io/hostname: pinode01
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "private internet access"
        - name: PIA_USER
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: PIA_USER
        - name: PIA_PASS
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: PIA_PASS
        - name: TZ
          value: "UTC"
        ports:
        - containerPort: 8888
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
