apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: default
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      nodeSelector:
        kubernetes.io/hostname: pinode01
      containers:
      - name: gluetun
        image: qmcgaw/private-internet-access:latest
        env:
        - name: PIA_USER
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: USERNAME
        - name: PIA_PASS
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: PASSWORD
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: default
spec:
  selector:
    app: gluetun
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
