apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: default
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      nodeSelector:
        kubernetes.io/hostname: pinode01
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        env:
        - name: VPNSP
          value: "private internet access"
        - name: PIA_USER
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: USERNAME
        - name: PIA_PASS
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: PASSWORD
        - name: TZ
          value: "UTC"
        ports:
        - containerPort: 8888
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
---
apiVersion: v1
kind: Secret
metadata:
  name: pia-creds
  namespace: default
type: Opaque
data:
  USERNAME: <base64-encoded-username>
  PASSWORD: <base64-encoded-password>
