apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "private internet access"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: USERNAME
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pia-creds
              key: PASSWORD
        ports:
        - containerPort: 51820
        - containerPort: 8888
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          privileged: true
