version: "3.9"
services:
  webserver:
    image: Dockerfile
    container_name: bbt-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/nvme/www/html:/var/www/html
      - -v /mnt/nvme/mysql:/var/lib/mysql
    ports:
      - 8000:80
