version: "3.9"
services:
  web:
    image: bbt-webserver
    container_name: bbt-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/bbt/www/html:/var/www/html
    ports:
      - 8000:80
