version: "3.9"
services:
  webserver:
    container_name: bbt-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/nvme/www/html:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - bbt-mysql

  bbt-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bbt
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
