# Use an official PHP runtime
#FROM php:8.2-apache
# Enable Apache modules
#RUN a2enmod rewrite
# Install any extensions you need
#RUN docker-php-ext-install mysqli pdo pdo_mysql
# Set the working directory to /var/www/html
#WORKDIR /var/www/html
# Copy the source code in /www into the container at /var/www/html
#COPY ../www .

FROM alpine:latest

RUN apk add lighttpd php82 fcgi php82-cgi --no-cache






