version: "3.9"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: bbt-phpmyadmin
    environment:
      UPLOAD_LIMIT: 300M
      PMA_HOST: mysql
      PMA_PORT: 30036
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80