version: '3.1'
services:  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - bbt-mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: admin