version: '3.1'
services:  
  phpmyadmin:
    platform: linux/arm64
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: bbt-website-bbt-mysql-1
      MYSQL_ROOT_PASSWORD: admin