version: '3'
services:
  portainer:
    image: cr.portainer.io/portainer/portainer-ee:latest
    container_name: portainer
    restart: always
    networks:
      - portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/AppPool/Docker/Portainer/data:/data
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      placement:
        constraints:
          - node.hostname==pinode00
