- hosts: "{{ variable_host | default('allnodes') }}"
  become: yes
  
  tasks:
    - name: Docker - Leave Swarm
      shell: |
        sudo docker swarm leave --force
      args:
        executable: /bin/bash
