- hosts: "{{ variable_host | default('allnodes') }}"
  become: yes

  vars:
    z_swarm_leader: "{{ groups['swarm_leader'][0] }}"

  tasks:
    - name: Docker - Leave Swarm with no logic
      shell: |
        sudo docker swarm leave --force
      args:
        executable: /bin/bash
      ignore_errors: true
    
    - name: Docker - Init swarm on the Swarm Leader
      community.general.docker_swarm:
        state: present
        advertise_addr: "{{ z_swarm_leader }}"
      register: result
      when: inventory_hostname == groups['swarm_leader'][0]
    
    - name: Debug Test
      debug:
        msg: "Swarm Leader: {{ z_swarm_leader }}"

    - name: Docker - Get Worker Token
      set_fact:
        join_token_worker: "{{ hostvars[groups['swarm_leader'][0]].result.swarm_facts.JoinTokens.Worker }}"

    - name: Check if Docker Swarm Token Variable is correct
      debug:
        msg: "Docker Swarm Worker Token: {{ join_token_worker }}"

    - name: Docker - Join Swarm Workers
      shell: |
        "docker swarm join --token {{ join_token_worker }} 10.200.1.90:2377"
      args:
        executable: /bin/bash
      when: inventory_hostname == groups['swarm_worker']