- hosts: "{{ variable_host | default('allnodes') }}"
  become: yes

  vars:
    ansible_host: "{{ groups['swarm_leader'][0] }}"

  tasks:
    - name: Init swarm on the first node
      community.general.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"
      register: result
      when: inventory_hostname == groups['swarm_leader'][0]
      debug:
        msg: "Ansible host is: {{ ansible_host }}"

    - name: Get join-token for worker nodes
      set_fact:
        join_token_worker: "{{ hostvars[groups['swarm_leader'][0]].result.swarm_facts.JoinTokens.Worker }}"

    - name: Join workers
      community.general.docker_swarm:
        state: join
        join_token: "{{ join_token_worker }}"
        advertise_addr: "{{ ansible_host }}"
        remote_addrs: "{{ hostvars[groups['swarm_leader'][0]].ansible_host }}"
      when:
        - inventory_hostname in groups['swarm_workers']