- hosts: "{{ variable_host | default('allnodes') }}"
  become: yes

  vars:
    z_swarm_leader: "{{ groups['swarm_leader'][0] }}"

  tasks:
    - name: Init swarm on the first node
      community.general.docker_swarm:
        state: present
        advertise_addr: "{{ z_swarm_leader }}"
      register: result
      when: inventory_hostname == groups['swarm_leader'][0]
    
    - name: Debug Test
      debug:
        msg: "Swarm Leader: {{ z_swarm_leader }}"

    - name: Get join-token for worker nodes
      set_fact:
        join_token_worker: "{{ hostvars[groups['swarm_leader'][0]].result.swarm_facts.JoinTokens.Worker }}"

    - name: Check if Docker Swarm Token Variable is correct
      debug:
        msg: "Docker Swarm Worker Token: {{ join_token_worker }}"

    - name: Join workers
      community.general.docker_swarm:
        state: join
        join_token: "{{ join_token_worker }}"
        advertise_addr: "{{ z_swarm_leader }}"
        remote_addrs: "{{ z_swarm_leader }}"
      when:
        - inventory_hostname in groups['swarm_workers']